name:                dice-entropy-conduit
version:             1.0.0.3
github:              "pwrobinson/dice-entropy-conduit"
license:             LGPL-2.1
author:              "Peter Robinson"
maintainer:          "pwr@lowerbound.io"
copyright:           "2014-2020 Peter Robinson"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Cryptographically secure n-sided dice via rejection sampling
category:            Data, Cryptography

description:         Please see the README on GitHub at <https://github.com/pwrobinson/dice-entropy-conduit#readme>


dependencies:
- base >= 4.6 && < 5
- bytestring >= 0.9
- entropy >= 0.3.2
- conduit >= 1.1.7
- transformers >= 0.4.0.0

library:
  source-dirs: src

tests:
  dice-entropy-conduit-test:
    main: Tests.hs
    source-dirs:
      - tests
      - src
    dependencies:
      - base >= 4 && < 5
      - QuickCheck >= 2.4
      - test-framework >= 0.4.1
      - test-framework-quickcheck2
